"use client";

/**
 * "Create New Subject" dialog (mirrors Streamlit create_subject_dialog).
 * The join code is generated by the server (security fix), so instead of a
 * "Subject Code" input the code + QR are shown right after creation.
 */
import { useCallback, useState } from "react";
import { Dialog, DialogContent, DialogHeader } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";
import { Alert, ErrorNotice } from "@/components/ui/feedback";
import { QrImage } from "@/components/QrImage";
import { createSubject } from "@/lib/endpoints";
import type { SubjectPublic } from "@/lib/types";

export function CreateSubjectDialog({
  open,
  onOpenChange,
  onCreated,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated: () => void;
}) {
  const [name, setName] = useState("");
  const [section, setSection] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<unknown>(null);
  const [created, setCreated] = useState<SubjectPublic | null>(null);

  const reset = useCallback(() => {
    setName("");
    setSection("");
    setError(null);
    setCreated(null);
    setSaving(false);
  }, []);

  const handleOpenChange = (next: boolean) => {
    if (!next) {
      if (created) onCreated();
      reset();
    }
    onOpenChange(next);
  };

  const submit = async () => {
    if (!name.trim() || !section.trim()) {
      setError(new Error("Please fill all the fields!"));
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const res = await createSubject({ name: name.trim(), section: section.trim() });
      setCreated(res.subject);
    } catch (e) {
      setError(e);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <DialogHeader
          title="Create New Subject"
          description={created ? "Subject Created Successfully!" : "Enter the details of new subject"}
        />

        {created ? (
          <div className="space-y-4">
            <p className="text-sm text-slate-600">
              {created.name} · Section {created.section} — share this code with your students:
            </p>
            <code className="block w-fit rounded-md bg-lavender px-4 py-1.5 text-xl font-semibold tracking-widest text-blurple">
              {created.subject_code}
            </code>
            <div className="flex flex-col items-center gap-1">
              {created.subject_code ? <QrImage subjectCode={created.subject_code} /> : null}
              <p className="text-xs text-slate-500">QRCODE for class joining</p>
            </div>
            <Button className="w-full" onClick={() => handleOpenChange(false)}>
              Done
            </Button>
          </div>
        ) : (
          <div>
            <Field label="Subject Name">
              <Input
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Introduction to Computer Science"
              />
            </Field>
            <Field label="Section">
              <Input value={section} onChange={(e) => setSection(e.target.value)} placeholder="A" />
            </Field>
            {error ? <ErrorNotice error={error} /> : null}
            <Alert variant="info" className="mt-2">
              A unique subject code is generated automatically when you create the subject.
            </Alert>
            <Button className="mt-4 w-full" onClick={submit} loading={saving}>
              Create Subject Now
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
